version: '2.2'
services:
  postgres:
    networks:
      crosscheck_default:
        ipv4_address: 172.18.0.3
  backend:
    ports:
      - "8182:8080"
    networks:
      crosscheck_default:
        ipv4_address: 172.18.0.6
  frontend:
    ports:
      - "4200:80"
    networks:
      crosscheck_default:
        ipv4_address: 172.18.0.4
  graphql-engine:
    ports:
      - "8090:8080"
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_INTERNAL_ERRORS: "true"
    networks:
      crosscheck_default:
        ipv4_address: 172.18.0.7
  minio:
    ports:
      - "9000:9000"
    networks:
      crosscheck_default:
        ipv4_address: 172.18.0.2
#      - "host.docker.internal:172.21.0.2"
  autoheal:
    networks:
      crosscheck_default:
        ipv4_address: 172.18.0.5

networks:
  crosscheck_default:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
