version: '3'
services:
  postgres:
    build: database/.
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - database-data_production:/var/lib/postgresql/data/ # persist data even if container shuts down
    expose:
      - 5433
    networks:
      - nginx-certbot-master_default
  backend:
    build: backend/.
    links:
      - postgres
    ports:
      - "8182:8080"
    depends_on:
      - "postgres"
    networks:
      - nginx-certbot-master_default
  frontend:
    build: frontend/.
    ports:
      - "4200:80"
    volumes:
       - ./frontend/config.json:/usr/share/nginx/html/config.json
    networks:
      - nginx-certbot-master_default

volumes:
  database-data_production: # named volumes can be managed easier using docker-compose
networks:
  nginx-certbot-master_default:
    external: true
