version: '2.2'
services:
  backend:
    ports:
      - "8182:8080"
  frontend:
    ports:
      - "4200:80"
  graphql-engine:
    ports:
      - "8090:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@crosscheck_database:5432/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${GRAPHQL_PASSWORD}
      HASURA_GRAPHQL_AUTH_HOOK: "http://crosscheck_backend:8080/be-cross-check/auth/hasura-role"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_INTERNAL_ERRORS: "true"
  minio:
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data