version: '2.2'
services:
  backend:
    ports:
      - "8182:8080"
  frontend:
    ports:
      - "4200:80"
  graphql-engine:
    ports:
      - "8090:8080"
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_INTERNAL_ERRORS: "true"
  minio:
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:172.21.0.2"