version: '3'
services:
  database:
    image: postgres:12
    container_name: crosscheck_database_backup
    restart: always
    volumes:
        - ./data-slave:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - 'POSTGRES_PASSWORD=my_password'
      - 'POSTGRES_DB=my_default_database'
