--
-- PostgreSQL database dump
--

-- Dumped from database version 12.4 (Debian 12.4-1.pgdg100+1)
-- Dumped by pg_dump version 12.4 (Debian 12.4-1.pgdg100+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    name text NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    priority text NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint,
    deleted_by bigint
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO postgres;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO postgres;

--
-- Name: questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questions (
    id bigint NOT NULL,
    question text NOT NULL,
    answer text NOT NULL,
    deleted boolean DEFAULT false,
    priority integer DEFAULT 2 NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    category_id integer,
    views_number integer DEFAULT 0,
    likes_number integer DEFAULT 0,
    created_by bigint,
    updated_by bigint,
    deleted_by bigint NOT NULL
);


ALTER TABLE public.questions OWNER TO postgres;

--
-- Name: faq_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.faq_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    name character varying(24) NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    role_id integer NOT NULL
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- Name: user_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    ais_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (id, name, created_at, updated_at, deleted_at, priority, deleted, created_by, updated_by, deleted_by) FROM stdin;
\.


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
0	LasticF	liquibase/changelog-2020-10-10-1.xml	2020-10-22 13:39:33.581409	1	EXECUTED	8:2032390b67f03fd9b57acfe316c736bb	createTable tableName=faq		\N	4.1.0	\N	\N	3366773470
0	LasticF	liquibase/changelog-2020-14-10-1.xml	2020-10-22 13:39:33.588265	2	EXECUTED	8:c33001e1916c4e7445a015ad95736662	renameTable newTableName=questions, oldTableName=faq		\N	4.1.0	\N	\N	3366773470
1	LasticF	liquibase/changelog-2020-14-10-1.xml	2020-10-22 13:39:33.602382	3	EXECUTED	8:3f0c3221dee591d1a71b966b37438136	createTable tableName=categories		\N	4.1.0	\N	\N	3366773470
2	LasticF	liquibase/changelog-2020-14-10-1.xml	2020-10-22 13:39:33.612702	4	EXECUTED	8:2a9bb2785bb89d203c3c89f94212d2f9	addColumn tableName=questions; addColumn tableName=questions; addColumn tableName=questions; addColumn tableName=questions; addColumn tableName=questions; addColumn tableName=questions		\N	4.1.0	\N	\N	3366773470
3	LasticF	liquibase/changelog-2020-14-10-1.xml	2020-10-22 13:39:33.619516	5	EXECUTED	8:e335fd2e8d044b7f7fb0cf01a61ca46c	addForeignKeyConstraint baseTableName=questions, constraintName=fk_questions_categories, referencedTableName=categories		\N	4.1.0	\N	\N	3366773470
0	LasticF	liquibase/changelog-2020-16-10-1.xml	2020-10-22 13:39:33.625929	6	EXECUTED	8:2d45ffc1c73d6ff9e9da6d4a2ad93745	dropDefaultValue columnName=priority, tableName=questions; addDefaultValue columnName=priority, tableName=questions		\N	4.1.0	\N	\N	3366773470
1	LasticF	liquibase/changelog-2020-16-10-1.xml	2020-10-22 13:39:33.639802	7	EXECUTED	8:bde4f04e07c54fa4641321f480cd3d9f	modifyDataType columnName=id, tableName=categories		\N	4.1.0	\N	\N	3366773470
2	LasticF	liquibase/changelog-2020-16-10-1.xml	2020-10-22 13:39:33.650593	8	EXECUTED	8:703f25e931aee7e1d9ecb306e953460c	createTable tableName=users		\N	4.1.0	\N	\N	3366773470
3	LasticF	liquibase/changelog-2020-16-10-1.xml	2020-10-22 13:39:33.662257	9	EXECUTED	8:4934114c7829e2d60e086bd09615dfde	createTable tableName=roles		\N	4.1.0	\N	\N	3366773470
4	LasticF	liquibase/changelog-2020-16-10-1.xml	2020-10-22 13:39:33.672247	10	EXECUTED	8:26bbe2a67d19035a213ad18e5c89d0da	insert tableName=roles; insert tableName=roles; insert tableName=roles; insert tableName=roles		\N	4.1.0	\N	\N	3366773470
5	LasticF	liquibase/changelog-2020-16-10-1.xml	2020-10-22 13:39:33.682192	11	EXECUTED	8:ad4c4e92479aac5919c24deaec7913a5	createTable tableName=user_roles		\N	4.1.0	\N	\N	3366773470
6	LasticF	liquibase/changelog-2020-16-10-1.xml	2020-10-22 13:39:33.691	12	EXECUTED	8:3214062554243073c5dec9c6b9cae442	addColumn tableName=questions; addColumn tableName=questions; addColumn tableName=questions; addColumn tableName=questions; addColumn tableName=questions		\N	4.1.0	\N	\N	3366773470
7	LasticF	liquibase/changelog-2020-16-10-1.xml	2020-10-22 13:39:33.700714	13	EXECUTED	8:b9eba7998db70c45458836e7abee07b4	addColumn tableName=categories; addColumn tableName=categories; addColumn tableName=categories; addColumn tableName=categories; addColumn tableName=categories		\N	4.1.0	\N	\N	3366773470
8	LasticF	liquibase/changelog-2020-16-10-1.xml	2020-10-22 13:39:33.715283	14	EXECUTED	8:1efb7de0167f6f0d2e10970a0d186063	addForeignKeyConstraint baseTableName=user_roles, constraintName=fk_users_roles_user, referencedTableName=users; addForeignKeyConstraint baseTableName=user_roles, constraintName=fk_users_roles_role, referencedTableName=roles; addForeignKeyConstrai...		\N	4.1.0	\N	\N	3366773470
\.


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- Data for Name: questions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.questions (id, question, answer, deleted, priority, created_at, updated_at, deleted_at, category_id, views_number, likes_number, created_by, updated_by, deleted_by) FROM stdin;
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, name) FROM stdin;
1	student
2	staff
3	admin
4	super_admin
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_roles (id, user_id, role_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, ais_id, created_at) FROM stdin;
\.


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_id_seq', 1, false);


--
-- Name: faq_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.faq_id_seq', 1, false);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 4, true);


--
-- Name: user_roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_roles_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: questions faq_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT faq_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: categories fk_categories_created_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fk_categories_created_by FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: categories fk_categories_deleted_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fk_categories_deleted_by FOREIGN KEY (deleted_by) REFERENCES public.users(id);


--
-- Name: categories fk_categories_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fk_categories_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id);


--
-- Name: questions fk_questions_categories; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fk_questions_categories FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: questions fk_questions_created_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fk_questions_created_by FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: questions fk_questions_deleted_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fk_questions_deleted_by FOREIGN KEY (deleted_by) REFERENCES public.users(id);


--
-- Name: questions fk_questions_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fk_questions_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id);


--
-- Name: user_roles fk_users_roles_role; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_users_roles_role FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: user_roles fk_users_roles_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_users_roles_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

